image: "scorpil/rust:stable"

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

.test: &test
    stage: test
    before_script:
        - apt update -yqq
        - apt install -yqq --no-install-recommends libgtk-3-dev
        - MODE=$(echo "$CI_JOB_NAME" | cut -d ':' -f 2)
        - test "$MODE" == "release" && CARGO_FLAGS='--release' || CARGO_FLAGS=''
    script:
        - rustc --version && cargo --version
        - cargo test --all-features $CARGO_FLAGS

test:debug:
    <<: *test

test:release:
    <<: *test

cache:
    paths:
        - $CARGO_HOME
        - target/
