[package]
name = "yellow-pitaya"
version = "0.1.0"
authors = ["Sanpi <sanpi@homecomputing.fr>"]
edition = "2018"

[dependencies]
cairo-rs = "0.14"
env_logger = "0.8"
gtk = "0.14"
log = "0.4"
redpitaya-scpi = "0.27"
relm = "0.22"
relm-derive = "0.22"
structopt = "0.3"
