on: [pull_request, push]

jobs:
  lint_fmt:
    name: cargo fmt
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
      - name: Check formating
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

  tests:
    name: Tests
    strategy:
      matrix:
        mode: ["debug", "release"]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install gtk
        run: |
          sudo apt update -yqq
          sudo apt install -yqq --no-install-recommends libgtk-3-dev

      - name: Run tests (debug)
        if: matrix.mode == 'debug'
        run: cargo test --all-features

      - name: Run tests (release)
        if: matrix.mode == 'release'
        run: cargo test --all-features --release
